Repository smaranjitghose/DeepPixel, pull requests merged in 2020-04, with the labels that each got.

#68 Updated .py File
  deeppixel/Diseased Leaf Classification/diseased_leaf_classification.py
Labels: rgsoc

#69 Updated Files
  deeppixel/Diseased Leaf Classification/diseased_leaf_classification.py
  deeppixel/denoise/requirements.txt
Labels: rgsoc

#73 Facial Expression Recognition
  deeppixel/facialEmotionRecog/FER_CNN.ipynb
  deeppixel/facialEmotionRecog/README.MD
Labels: jupyter, rgsoc

#79 Updated README.md
  deeppixel/Rock paper scissor/README.md
Labels: PR: unreviewed, documentation, rgsoc

#81 Updated readme for object_detection
  deeppixel/object_detection/README.md
Labels: PR: unreviewed, documentation, rgsoc

#80 Developed Script for age _and_gender_detection
  deeppixel/face_rec/Age_and_gender_detection/AgeAndGenderImage.py
  deeppixel/face_rec/Age_and_gender_detection/AgeAndGenderVideo.py
  deeppixel/face_rec/Age_and_gender_detection/AgeAndGenderWebcam.py
  deeppixel/face_rec/Age_and_gender_detection/README.md
  deeppixel/face_rec/Age_and_gender_detection/asset/input/girl.jpeg
  deeppixel/face_rec/Age_and_gender_detection/asset/input/group.jpeg
  deeppixel/face_rec/Age_and_gender_detection/asset/input/woman.jpeg
  deeppixel/face_rec/Age_and_gender_detection/asset/output/girl.png
  deeppixel/face_rec/Age_and_gender_detection/asset/output/girl1.png
  deeppixel/face_rec/Age_and_gender_detection/asset/output/group.png
  deeppixel/face_rec/Age_and_gender_detection/asset/output/input.png
  deeppixel/face_rec/Age_and_gender_detection/asset/output/kid1.png
  deeppixel/face_rec/Age_and_gender_detection/asset/output/man1.png
  deeppixel/face_rec/Age_and_gender_detection/asset/output/woman.png
  deeppixel/face_rec/Age_and_gender_detection/asset/output/woman1.png
  requirements.txt
Labels: PR: unreviewed, documentation, rgsoc, script

#85 Developed Colab Notebook for Image Subset Detection
  deeppixel/imgSubsetDetection/images/input/cars.jpg
  deeppixel/imgSubsetDetection/images/input/cups.jpg
  deeppixel/imgSubsetDetection/images/input/subset_car.jpg
  deeppixel/imgSubsetDetection/images/input/subset_cup.jpg
  deeppixel/imgSubsetDetection/images/input/subset_tree.jpg
  deeppixel/imgSubsetDetection/images/input/subset_window.jpg
  deeppixel/imgSubsetDetection/images/input/trees.jpg
  deeppixel/imgSubsetDetection/images/input/windows.jpg
  deeppixel/imgSubsetDetection/images/output/car_output.png
  deeppixel/imgSubsetDetection/images/output/cups_output.png
  deeppixel/imgSubsetDetection/images/output/trees_output.png
  deeppixel/imgSubsetDetection/images/output/windows_output.png
  deeppixel/imgSubsetDetection/readme.md
  deeppixel/imgSubsetDetection/subset_detection.ipynb
Labels: PR: unreviewed, jupyter, rgsoc20

#92 Updated Age_and_gender_detection
  deeppixel/face_rec/Age_and_gender_detection/AgeAndGenderVideo.py
  deeppixel/face_rec/Age_and_gender_detection/README.md
Labels: PR: unreviewed, enhancement, rgsoc20

#89 Created a model for text recognition
  deeppixel/Text_Recognition/Input/OCR1.png
  deeppixel/Text_Recognition/Input/OCR2.jpg
  deeppixel/Text_Recognition/readme.md
  deeppixel/Text_Recognition/text_recog.py
Labels: PR: unreviewed, rgsoc20, script

#91 Developed script for face_anonymization
  deeppixel/face_anonymization/README.md
  deeppixel/face_anonymization/asset/input/kid1.jpg
  deeppixel/face_anonymization/asset/input/video_billie.mp4
  deeppixel/face_anonymization/asset/input/woman.jpeg
  deeppixel/face_anonymization/asset/input/woman1.jpg
  deeppixel/face_anonymization/asset/output/input.png
  deeppixel/face_anonymization/asset/output/kid1.png
  deeppixel/face_anonymization/faceAnonymizationImage.py
  deeppixel/face_anonymization/faceAnonymizationVideo.py
  deeppixel/face_anonymization/faceAnonymizationWebcam.py
Labels: PR: unreviewed, documentation, rgsoc20, script

#96 Developed script for image subset detection
  deeppixel/imgSubsetDetection/multiple_instance.py
  deeppixel/imgSubsetDetection/readme.md
  deeppixel/imgSubsetDetection/requirements.txt
  deeppixel/imgSubsetDetection/single_instance.py
Labels: PR: unreviewed, rgsoc20, script

#97 Added Motion_detection.py script and updated requirements.txt
  deeppixel/Motion_detection/motion_detection.py
  deeppixel/Motion_detection/requirements.txt
Labels: PR: unreviewed, documentation, rgsoc20, script

#98 Image Stitching (#93)
  deeppixel/image_stitching/README.md
  deeppixel/image_stitching/input/IMG_1786-2.jpg
  deeppixel/image_stitching/input/IMG_1787-2.jpg
  deeppixel/image_stitching/input/IMG_1788-2.jpg
  deeppixel/image_stitching/output/output.png
  deeppixel/image_stitching/requirements.txt
  deeppixel/image_stitching/stitched.py
Labels: PR: unreviewed, rgsoc20, script

#100 Update README.md
  deeppixel/img_undark/README.md
Labels: PR: unreviewed, bug, rgsoc20
