Repository smaranjitghose/DeepPixel, pull requests merged in 2020-03, with the labels that each got.

#10 Implementation of Face detection in pictures #5
  deeppixel/Face_Detection/Face_Detect.ipynb
  deeppixel/Face_Detection/Output_images/image1.png
  deeppixel/Face_Detection/README.md
  deeppixel/Face_Detection/Sample_images/emma.jpg
  deeppixel/Face_Detection/Sample_images/group.jpeg
  deeppixel/Face_Detection/Sample_images/run2.jpeg
  deeppixel/Face_Detection/Sample_images/running.jpeg
  deeppixel/Face_Detection/haarcascade_frontalface_alt.xml
Labels: rgsoc

#11 Script to implement Black and White to Color
  deeppixel/bw_to_c/README.MD
  deeppixel/bw_to_c/colorization.py
  deeppixel/bw_to_c/image_colorization.ipynb
  deeppixel/bw_to_c/input/dog.jpg
  deeppixel/bw_to_c/input/horse.jpg
  deeppixel/bw_to_c/input/lion.jpg
  deeppixel/bw_to_c/model/colorization_deploy_v2.prototxt
  deeppixel/bw_to_c/model/pts_in_hull.npy
  deeppixel/bw_to_c/output/dog.png
  deeppixel/bw_to_c/output/horse.png
  deeppixel/bw_to_c/output/lion.png
  deeppixel/bw_to_c/requirements.txt
  deeppixel/bw_to_c/test_images/lake.png
Labels: rgsoc

#13 Updated README.md
  README.md
Labels: documentation, rgsoc

#16 Solved #7 (Implement Artistic Style Transfer )
  deeppixel/artistic_style_transfer/README.MD
  deeppixel/artistic_style_transfer/style_transfer_using_Pytorch.ipynb
  style_transfer.ipynb
Labels: rgsoc

#18 Image Denoising
  deeppixel/denoise/Image_Denoising_01.ipynb
  deeppixel/denoise/Input/Blurred/FG_1.png
  deeppixel/denoise/Input/Flower.png
  deeppixel/denoise/Input/High Frequency Component/Embossed.png
  deeppixel/denoise/Output/Bilateral Filtering/Bilateral.png
  deeppixel/denoise/Output/FlowerDenoised.png
  deeppixel/denoise/Output/data.npy
  deeppixel/denoise/README.MD
Labels: rgsoc

#30 Documentation of the project (#25)
  README.md
  deeppixel/Face_Detection/README.md
  deeppixel/artistic_style_transfer/README.MD
  deeppixel/bw_to_c/README.MD
  deeppixel/denoise/README.MD
  docs/index.html
Labels: documentation, rgsoc

#28 Face detect
  deeppixel/Face_Detection/.ipynb_checkpoints/Face_Detect-checkpoint.ipynb
  deeppixel/Face_Detection/FaceDetection.py
  deeppixel/Face_Detection/README.md
  deeppixel/Face_Detection/Sample_output/run2.png
Labels: build, rgsoc, script

#31 Facerec3
  deeppixel/face_rec/Face_detection/FaceDetection.py
  deeppixel/face_rec/Face_detection/README.md
  deeppixel/face_rec/Face_detection/Sample_images/emma.jpg
  deeppixel/face_rec/Face_detection/Sample_images/group.jpeg
  deeppixel/face_rec/Face_detection/Sample_images/run2.jpeg
  deeppixel/face_rec/Face_detection/Sample_images/running.jpeg
  deeppixel/face_rec/Face_detection/Sample_output/group.png
  deeppixel/face_rec/Face_detection/Sample_output/run2.png
  deeppixel/face_rec/Face_detection/haarcascade_frontalface_alt.xml
  deeppixel/face_rec/Face_detection/requirements.txt
  deeppixel/face_rec/Face_detection_real_time/FaceDetectRealTime.py
  deeppixel/face_rec/Face_detection_real_time/README.md
  deeppixel/face_rec/Face_detection_real_time/haarcascade_frontalface_alt.xml
  deeppixel/face_rec/Face_detection_real_time/requirements.txt
Labels: rgsoc, script

#34 Solve #21 (Image Similarity )
  deeppixel/Image Similarity/ImageSimilarity.py
  deeppixel/Image Similarity/images/modified_01.png
  deeppixel/Image Similarity/images/modified_02.png
  deeppixel/Image Similarity/images/modified_03.png
  deeppixel/Image Similarity/images/original_01.png
  deeppixel/Image Similarity/images/original_02.png
  deeppixel/Image Similarity/images/original_03.png
  deeppixel/Image Similarity/readme.md
Labels: build, rgsoc, script

#37 Facerec3
  deeppixel/face_rec/Face_detection/README.md
  deeppixel/face_rec/Face_detection_real_time/README.md
Labels: documentation, rgsoc

#40 Modified the Image Similarity code (#21)
  deeppixel/Image Similarity/ImageSimilarity.py
  deeppixel/Image Similarity/readme.md
Labels: enhancement, rgsoc

#35 Script for Image illumination
  deeppixel/image_illumination/README.md
  deeppixel/image_illumination/image_illumination.py
  deeppixel/image_illumination/input/1.jpg
  deeppixel/image_illumination/input/2.jpg
  deeppixel/image_illumination/input/3.jpg
  deeppixel/image_illumination/input/4.jpg
  deeppixel/image_illumination/input/5.jpg
  deeppixel/image_illumination/input/6.jpg
  deeppixel/image_illumination/input/7.jpg
  deeppixel/image_illumination/input/8.jpg
  deeppixel/image_illumination/output/1.jpg
  deeppixel/image_illumination/output/2.jpg
  deeppixel/image_illumination/output/3.jpg
  deeppixel/image_illumination/output/4.jpg
  deeppixel/image_illumination/output/5.jpg
  deeppixel/image_illumination/output/6.jpg
  deeppixel/image_illumination/output/7.jpg
  deeppixel/image_illumination/output/8.jpg
  deeppixel/image_illumination/requirements.txt
Labels: rgsoc

#36 Objdet
  deeppixel/Object_Detection/ObjectDetection.py
  deeppixel/Object_Detection/README.md
  deeppixel/Object_Detection/asset/input/apple.jpeg
  deeppixel/Object_Detection/asset/input/image.jpg
  deeppixel/Object_Detection/asset/output/apple.png
  deeppixel/Object_Detection/asset/output/image.png
  deeppixel/Object_Detection/requirements.txt
Labels: rgsoc

#44 Image Captioning(#20)
  deeppixel/Image_Captioning/README.md
  deeppixel/Image_Captioning/captioning.ipynb
  deeppixel/Image_Captioning/input/218342358_1755a9cce1.jpg
  deeppixel/Image_Captioning/input/2513260012_03d33305cf.jpg
  deeppixel/Image_Captioning/input/2644326817_8f45080b87.jpg
  deeppixel/Image_Captioning/input/2699342860_5288e203ea.jpg
  deeppixel/Image_Captioning/input/488416045_1c6d903fe0.jpg
  deeppixel/Image_Captioning/output/1.png
  deeppixel/Image_Captioning/output/2.png
  deeppixel/Image_Captioning/output/3.png
  deeppixel/Image_Captioning/requirements.txt
Labels: build, jupyter, rgsoc

#55 Update index.html
  docs/index.html
Labels: documentation, rgsoc
