Repository smaranjitghose/DeepPixel, pull requests merged in 2020-08, with the labels that each got.

#107 Added GradCAM and BaseCAM (along with a test)
  deeppixel/cam/basecam.py
  deeppixel/cam/gradcam.py
  deeppixel/cam/utils.py
Labels: PR: unreviewed

#112 Added Gradcam++ and README.MD file
  Test/deeppixel/cam/bull_mastiff.png
  Test/deeppixel/cam/gradcam_test.py
  Test/deeppixel/cam/gradcampp_test.py
  deeppixel/cam/README.MD
  deeppixel/cam/gradcam.py
  deeppixel/cam/gradcampp.py
Labels: PR: unreviewed

#114 Added ScoreCAM and SSCAM
  Test/deeppixel/cam/scorecam_test.py
  Test/deeppixel/cam/smoothgradcampp_test.py
  Test/deeppixel/cam/sscam_test.py
  deeppixel/cam/README.MD
  deeppixel/cam/scorecam.py
  deeppixel/cam/smoothgradcampp.py
  deeppixel/cam/sscam.py
Labels: PR: unreviewed, explainable-cv, psoc2020

#115 Resolved file path issues on windows & linux
  deeppixel/cam/utils.py
  deeppixel/edge_detection/hed.py
  deeppixel/iqa/brisque.py
Labels: bug

#119 Added GradCAM
  deeppixel/cam/__init__.py
  deeppixel/cam/cam.py
  deeppixel/cam/gradcam.py
Labels: CH-20, Medium, PR: partially-approved

#120 Added GramCAM++
  deeppixel/cam/__init__.py
  deeppixel/cam/cam.py
  deeppixel/cam/gradcam.py
  deeppixel/cam/gradcampp.py
Labels: CH-20, Medium
